# Generated by Django 2.1.7 on 2020-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200526_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(default=None, to='orders.OrderItem'),
        ),
    ]
